### ISSUE TITLE
Unable to install Beta4 from iso

### ISSUE THREAD

**Issue by robcsi** [instantOS/instantOS#57]
I'm trying to install the latest iso, but I encounter system updating problems.

Setup:
- VirtualBox and ThinkPad T410 with USB stick
- standard internet connection, wifi, very good speed that shouldn't be a problem
- located in Romania

Issues:
The Install process first wants to do a full system upgrade and it is there it fails:
 - packages.instantos.io port 80: Connection refused
 - failed retrieving file 'instant.db'
 - not being able to download some packages from neither of the mirrors (I couldn't really catch some specific output here...)
 - if I close (Ctrl+C) the installation script, yay cannot update because the db is locked
 - it manages to update some packages if I delete *.db from /var/lib/pacman/sync folder; I then run yay again, but not a complete upgrade is done
 - when I run yay, sometimes it says: "could not open file /var/lib/pacman/sync/core.db: gzip decompression failed \n could not read db 'community' (Damaged tar archive)"
 - yay stops many times at downloading the 'linux-firmware-20200817.7a30af1-1-any.pkg.tar.zst' file from any mirror: "Failure to output to destination--------C" almost middle way in the progress bar, 43%.

I'm not sure why all this happens, is it my internet connection, my environments...

Anyone else encountered similar issues?

Thanks,
Robert

**Comment by paperbenni** [comment]
The primarry mirror was down for a while, it should be working again now

**Comment by robcsi** [comment]
I still get a "downloading instant db... \n could not read db '...' (Damaged tar archive) when I start the Install process.
yay gives me the same thing...

Other messages seen:
 - one regarding a signature being corrupted for git2.28.....pkg.zst and it not being able to download git 2.28 package.
 - some other saying "error: target not found: git"

It keeps on going without stopping after a lot of retries.

The iso being 1.2 GBs, couldn't it bring a more updated system? Why does is have to do such a big system upgrade before installing? Why can't it just install what's in the iso and upgrade later?
I'm not a big distro-creating expert, just asking...

**Comment by robcsi** [comment]
It seems to be because of the wifi connection. I get no errors if I plug in an ethernet cable...

**Comment by robcsi** [comment]
I'm passed that phase now, but it fails when trying to get the instant*...pkg.zst files.
Error: "The requested URL returned error: 404", for all the 5 categories, all 4 URLs.

**Comment by paperbenni** [comment]
The mirror that I replaced the primary one with while it was down turned out to be outdated. 
The installer now fetches a list of fallback mirrors before beginning the installation so now it should work. 
As for what it's downloading, it's not updating, it's actually downloading the OS onto the drive, meaning that it will always install the latest version. The live iso is mostly because a) people are used to that way of installation and b) because I want to offer that "test drive and then install" experience. You can also run the installer off a minimal arch iso if you want to, instructions can be found here. 
An offline installation option that just copies the files from the live iso to the file system will is planned but for a beta, having the option to adjust the install process without having to release a new iso every time is way better. 
And yes, because it is a net install, ethernet is highly recommended.

**Comment by paperbenni** [comment]
> yay stops many times at downloading the 'linux-firmware-20200817.7a30af1-1-any.pkg.tar.zst' file from any mirror: "Failure to output to destination--------C" almost middle way in the progress bar, 43%.
By the way, updating the live iso itself downloads the files to RAM (live isos are non-persistent) instead of a disk and once it runs out weird things can happen...
You should reboot the live iso before trying again to clean all temporary files

**Comment by paperbenni** [comment]
Ok, the problem seems to be much more serious. The main server got hacked and used to brute force ssh passwords of some companies. This led to it getting taken down for a while and being added to multiple block lists. The attack seems to have been automated and all files are intact. I will definitely need to improve security on it or change host

**Comment by robcsi** [comment]
> The mirror that I replaced the primary one with while it was down turned out to be outdated.
> The installer now fetches a list of fallback mirrors before beginning the installation so now it should work.
> As for what it's downloading, it's not updating, it's actually downloading the OS onto the drive, meaning that it will always install the latest version. The live iso is mostly because a) people are used to that way of installation and b) because I want to offer that "test drive and then install" experience. You can also run the installer off a minimal arch iso if you want to, instructions can be found [here](https://instantos.io/download#cli-installer).
> An offline installation option that just copies the files from the live iso to the file system will is planned but for a beta, having the option to adjust the install process without having to release a new iso every time is way better.
> And yes, because it is a net install, ethernet is highly recommended.

An offline installer would be welcome, in my opinion, especially if an ethernet connection is recommended for a net install. I image many people, me included, would want to try this on their laptop, in a VM, on the go, not necessarily having access to ethernet, but rather just wifi. Yes, the ISO would be larger, but there are advantages...

**Comment by robcsi** [comment]
> Ok, the problem seems to be much more serious. The main server got hacked and used to brute force ssh passwords of some companies. This led to it getting taken down for a while and being added to multiple block lists. The attack seems to have been automated and all files are intact. I will definitely need to improve security on it or change host

Wow, OK. That's not fun...

**Comment by robcsi** [comment]
It installed successfully now.

Thanks for the assistance. Hope you fix the hacked server.
